name: legendsofruneterra
version: '1.0'
summary: Make your move, and be legendary in the League of Legends strategy card game.
description: |
  Legends of Runeterra is a free-to-play digital collectible card game developed and published by Riot Games. Runeterra was released in open beta for Microsoft Windows on January 24, 2020. The game exists in the same universe as League of Legends, a multiplayer online battle arena game by Riot.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: amd64
base: core20
compression: lzo

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-staging
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

environment:
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  INSTALL_URL: "https://bacon.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.live.americas.exe"
  TRICKS: "d3dx9 dxvk194"
  LC_ALL: "C.UTF-8"
  NO_AT_BRIDGE: "1"
  DISABLE_WAYLAND: "1"
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

layout:
  /usr/share/libdrm:
    bind: $SNAP/wine-runtime/usr/share/libdrm
  /etc/alsa/conf.d:
    bind: $SNAP/wine-runtime/etc/alsa/conf.d

apps:
  legendsofruneterra:
    command: bin/wrapper
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - audio-playback
      - x11
      - gtk-3-themes
      - icon-themes
      - wine-runtime
      - wine-5-staging
  legendsofruneterranv:
    command: bin/wrapper
    environment:
      __NV_PRIME_RENDER_OFFLOAD: "1"
      __GLX_VENDOR_LIBRARY_NAME: "nvidia"
      __VK_LAYER_NV_optimus: "NVIDIA_only"
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - audio-playback
      - x11
      - gtk-3-themes
      - icon-themes
      - wine-runtime
      - wine-5-staging
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/wineboot
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/winecfg
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  wineserver:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/wineserver
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-runtime/bin/winetricks
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
  regedit:
    command: bin/sommelier $SNAP/wine-platform/wine-staging/bin/regedit
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  glxinfo:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/glxinfo
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  glxheads:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/glxheads
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  vulkaninfo:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vulkaninfo
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  vkcube:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vkcube
    environment:
      VK_INSTANCE_LAYERS: "VK_LAYER_MESA_overlay"
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
  vkcube-nv:
    command: bin/sommelier $SNAP/wine-runtime/usr/bin/vkcube
    environment:
      __NV_PRIME_RENDER_OFFLOAD: "1"
      __GLX_VENDOR_LIBRARY_NAME: "nvidia"
      __VK_LAYER_NV_optimus: "NVIDIA_only"
      VK_INSTANCE_LAYERS: "VK_LAYER_MESA_overlay"
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - x11

parts:
  legendsofruneterra:
    plugin: dump
    source: ./snap/local/scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-runtime
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'lolfix': bin/
      'sommelier': bin/
      'wrapper': bin/
